---
- name: Install Prowler on Ubuntu
  hosts: prowler-target
  become: yes

  vars:
    prowler_dir: /home/ubuntu/prowler
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    docker_list: /etc/apt/sources.list.d/docker.list
    docker_apt_repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"


  tasks:

    - name: Ensure required packages are installed (git, rsync, wget, curl)
      apt:
        name:
          - git
          - rsync
          - wget
          - curl
        state: present
        update_cache: yes

    - name: Install ca-certificates and curl for Docker GPG
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create Docker keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: "{{ docker_gpg_url }}"
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        filename: docker
        state: present
        update_cache: yes

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Create Prowler directory
      file:
        path: "{{ prowler_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Download Prowler docker-compose.yml
      get_url:
        url: https://raw.githubusercontent.com/prowler-cloud/prowler/refs/heads/master/docker-compose.yml
        dest: "{{ prowler_dir }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Download Prowler .env file
      get_url:
        url: https://raw.githubusercontent.com/prowler-cloud/prowler/refs/heads/master/.env
        dest: "{{ prowler_dir }}/.env"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Run docker compose up -d in Prowler directory
      become: true
      become_user: ubuntu
      command: docker compose up -d
      args:
        chdir: "{{ prowler_dir }}"