services:
  nginx:
    image: nginx:latest
    container_name: nginx-uptimerobot
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik-proxy      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.status.rule=Host(`status.machinesarehere.in`)"
      - "traefik.http.routers.status.entrypoints=websecure"      
      - "traefik.http.routers.status-secure.rule=Host(`status.machinesarehere.in`)"
      - "traefik.http.routers.status-secure.tls=true"
      - "traefik.http.routers.status-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.status.loadbalancer.server.port=80"
      - "traefik.http.routers.status-secure.middlewares=status-auth"
      - "traefik.http.routers.status.middlewares=status-auth"
      - "traefik.http.middlewares.status-auth.basicauth.users=${PASSWORD}"

networks:
  traefik-proxy:
    external: true