---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./appdata:/config
      - ./Downloads:/downloads
    ports:
      - localhost:8080:8080
      - localhost:6881:6881
      - localhost:6881:6881/udp
    restart: unless-stopped
    networks:
      - traefik-proxy      
    security_opt:
      - no-new-privileges:true        
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.torrent.entrypoints=http"
      - "traefik.http.routers.torrent.rule=Host(`torrent.machinesarehere.in`)"
      - "traefik.http.routers.torrent-secure.entrypoints=https"
      - "traefik.http.routers.torrent-secure.rule=Host(`torrent.machinesarehere.in`)"
      - "traefik.http.routers.torrent-secure.tls=true"
      - "traefik.http.routers.torrent-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.torrent.loadbalancer.server.port=8080"

networks:
  traefik-proxy:
    external: true         

