---
- name: Deploy Cilium CNI via Helm (only on master1)
  hosts: master1
  become: true

  pre_tasks:
    - name: Download Helm binary
      shell: curl -fsSL https://get.helm.sh/helm-v3.17.4-linux-amd64.tar.gz -o /tmp/helm.tar.gz
      args:
        creates: /tmp/helm.tar.gz

    - name: Extract Helm binary
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Move Helm binary to /usr/local/bin
      command: mv /tmp/linux-amd64/helm /usr/local/bin/helm

    - name: Set executable permission on Helm binary
      file:
        path: /usr/local/bin/helm
        mode: '0755'
        
    - name: Ensure Helm is in PATH
      shell: helm version
      register: helm_check

    - name: Debug Helm Version
      debug:
        var: helm_check.stdout

  tasks:
    - name: Install Cilium CNI
      shell: |
        helm install cilium cilium/cilium --version 1.18.0 \
          --namespace kube-system \
          --set ipam.mode=cluster-pool \
          --set ipam.operator.clusterPoolIPv4PodCIDR="10.50.0.0/16" \
          --set ipam.operator.clusterPoolIPv4MaskSize=24 \
          --set kubeProxyReplacement=true \
          --set hubble.relay.enabled=true \
          --set hubble.ui.enabled=true \
          --set prometheus.enabled=true \
          --set operator.prometheus.enabled=true \
          --set hubble.enabled=true \
          --set hubble.metrics.enableOpenMetrics=true \
          --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2}" \
          --set hubble.metrics.httpV2.exemplars=true \
          --set hubble.metrics.httpV2.labelsContext="{source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction}"
      args:
        creates: /etc/cilium-installed
      register: cilium_result

    - name: Mark Cilium as installed
      file:
        path: /etc/cilium-installed
        state: touch

    - name: Show Cilium Helm result
      debug:
        var: cilium_result.stdout_lines