---
- name: Deploy Cilium CNI via Helm (only on master1)
  hosts: master1
  become: true

  tasks:
    - name: Install Cilium CNI
      shell: |
        helm install cilium cilium/cilium --version 1.18.0 \
          --namespace kube-system \
          --set ipam.mode=cluster-pool \
          --set ipam.operator.clusterPoolIPv4PodCIDR="10.50.0.0/16" \
          --set ipam.operator.clusterPoolIPv4MaskSize=24 \
          --set kubeProxyReplacement=true \
          --set hubble.relay.enabled=true \
          --set hubble.ui.enabled=true \
          --set prometheus.enabled=true \
          --set operator.prometheus.enabled=true \
          --set hubble.enabled=true \
          --set hubble.metrics.enableOpenMetrics=true \
          --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2}" \
          --set hubble.metrics.httpV2.exemplars=true \
          --set hubble.metrics.httpV2.labelsContext="{source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction}"
      args:
        creates: /etc/cilium-installed
      register: cilium_result

    - name: Mark Cilium as installed
      file:
        path: /etc/cilium-installed
        state: touch

    - name: Show Cilium Helm result
      debug:
        var: cilium_result.stdout_lines