loki:
  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem   # use PVC instead of S3

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    reject_old_samples: false
    reject_old_samples_max_age: 168h
    ingestion_rate_mb: 16
    ingestion_burst_size_mb: 32

  ruler:
    enable_api: true

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi   # adjust to your storage needs
    storageClass: longhorn   # or whatever storageClass you use

# explicitly zero out other modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0      

# disable caching components (not needed for SingleBinary Loki)
resultsCache:
  enabled: false
chunksCache:
  enabled: false
memcached:
  enabled: false
memcachedExporter:
  enabled: false